const { fileName, filePath } = require("./utils/file");

const DISCLAIMER =
  `/**
 * THIS FILE IS AUTOGENERATED ON EACH BUILD
 * DO NOT CHANGE THE CONTENTS OF THIS FILE
 * CHANGES MADE IN THIS FILE WILL BE OVERWRITTEN DURING THE NEXT BUILD
 */`;
const HEADING = (file) => {
  const heading =
    `/**
 * ${fileName(file).toUpperCase()}
 */`;

  return heading;
};

const parseExportable = (exportable, file, { indent = "space", indentSize = 2 }) => {
	const spacer = indent === "space" ? new Array(indentSize).join(" ") : "\t";

  switch (exportable) {
    case "default":
      return `${spacer}default as ${fileName(file)},`;
    default:
      return `${spacer}${exportable},`;
  }
};

module.exports.createIndex = (exportables, options, dir) => [
  DISCLAIMER,
  "\n\n",
  ...exportables.map(({
    file,
    matches
  }) => {
    const src = filePath(file, dir);

    return [
      HEADING(file),
      "export {",
      ...matches.map((match) => parseExportable(match, file, options)),
      `} from './${src}';`,
      "\n"
    ].join("\n");
  }),
].join("");
