const { fileName, filePath } = require("./utils/file");

const DISCLAIMER =
  `/**
 * THIS FILE IS AUTOGENERATED ON EACH BUILD
 * DO NOT CHANGE THE CONTENTS OF THIS FILE
 * CHANGES MADE IN THIS FILE WILL BE OVERWRITTEN DURING THE NEXT BUILD
 */`;
const HEADING = (file) => {
  const heading =
    `/**
 * ${fileName(file).toUpperCase()}
 */`;

  return heading;
};

const parseExportable = (exportable, file) => {
  switch (exportable) {
    case "default":
      return `\tdefault as ${fileName(file)}Defaults,`;
    default:
      return `\t${exportable},`;
  }
};

module.exports.createIndex = (exportables, dir) => [
  DISCLAIMER,
  "\n\n",
  ...exportables.map(({
    file,
    matches
  }) => {
    const src = filePath(file, dir);

    return [
      HEADING(file),
      "export {",
      ...matches.map((match) => parseExportable(match, file)),
      `} from './${src}';`,
      "\n"
    ].join("\n");
  }),
].join("");
